// copy.js — UI strings, TH/EN. Tone per designlanguage.md v1.1 (pronoun always "คุณ").
const COPY = {
  th: {
    issue: "ISSUE #01 · 1998 → 2026",
    coverLine1: "ฉบับพิเศษ! อดีตชาติ",
    coverLine2: "สีมงคลวันนี้ ข้างในเล่ม ✦",
    headline1: "ชาติที่แล้ว",
    headline2: "คุณเคยเป็นอะไร?",
    subHook: "หาคำตอบกันง่าย ๆ ใน 60 วินาที",
    statusLive: "อัปเดต",
    statusNum: "148,290",
    statusText: "วิญญาณค้นพบแล้ว",
    todayChip: (c) => `สีมงคลวันนี้: ${c}`,
    birthdayTitle: "เช็คราศีตามวันเกิด",
    dayLabel: "วันที่",
    monthLabel: "เดือน",
    resultHint: "เลือกวันที่กับเดือน แล้วดูราศีได้เลย ✨",
    westernZodiac: "ราศีแบบตะวันตก",
    weekdayCaption: "เกิดวันอะไร? (ไม่บังคับ · ใช้หาสีประจำวันเกิด)",
    privacyLine: "ใช้แค่เช็คราศีกับสีนะ ไม่เก็บชื่อ ไม่ต้องล็อกอิน",
    startCta: "ปลดล็อคอดีตชาติ →",
    startDisabled: "เลือกวันเกิดก่อนน้า",
    decDay: "ลดวันที่", incDay: "เพิ่มวันที่", decMonth: "ลดเดือน", incMonth: "เพิ่มเดือน",
    dialAria: (s) => `วงล้อราศี: ${s}`,
    backAria: "ย้อนกลับ",
    langSwitchAria: "Switch to English",
    langOther: "EN",
    prev: "ย้อนกลับ",
    next: "ถัดไป",
    nextDisabled: "เลือกก่อนน้า",
    seeResult: "ดูผลเลย!",
    loadingCopy: "กำลังสุ่มการ์ดอดีตชาติ…",
    loadingTop: "SOULZINE",
    loadingTravel: "TRAVELLING 1998 → 2026",
    loadingBar: "LOADING",
    resultEyebrow: "SOULZINE · ISSUE #01",
    resultTitle: "การ์ดชาติก่อน",
    tabs: ["การ์ด", "ตัวตน", "ไลฟ์สไตล์", "เทียบ"],
    revealIntro: "ชาติที่แล้วคุณคือ…",
    rarityTier: "★ ULTRA RARE",
    rarityNote: (p) => `หายากระดับ ${p}%`,
    sampleData: "ข้อมูลตัวอย่าง",
    tagFun: "เอาฮา",
    tagEvidence: "มีแหล่งอ้างอิง",
    tagTradition: "ความเชื่อไทย",
    blockBirthday: "ตัวตนจากวันเกิด",
    elementLabel: "ธาตุประจำราศี",
    thaiDayLabel: "สีประจำวันเกิด",
    horoscopeLabel: "ดวงย่อ ๆ",
    blockBrief: "ตัวตนย่อ ๆ",
    blockToday: (d) => `สีมงคลวันนี้ · ${d}`,
    todayHeadline: "สีนำโชคของวันนี้",
    todaySource: (y) => `ที่มา: Hua Seng Hong · สีเสื้อมงคล ${y}`,
    todayExpired: (y) => `ตาราง ${y} หมดอายุแล้ว รออัปเดตปีใหม่`,
    blockPop: "Pop-Soul Match",
    popSong: "เพลงประจำวิญญาณ", popMovie: "หนังที่ใช่", popPlace: "เที่ยวไหนดี",
    popDecades: "80s → 20s",
    reroll: "สุ่มใหม่",
    blockEat: "กินตามสีมงคล",
    eatCaption: (c) => `จากสีนำโชควันนี้ (${c}) · เล่นสนุกตามสีนะ ไม่ใช่ใบสั่งอาหาร`,
    blockZen: "พักใจแบบเซน",
    zenStart: "เริ่ม 3 นาที",
    zenStop: "หยุด",
    zenAgain: "อีกรอบ",
    blockSelfCare: "ทิปดูแลตัวเองเบา ๆ",
    blockGoodToKnow: "รู้ไว้ก็ดี",
    labelHealthyEating: "กินดีแบบง่าย ๆ",
    labelHolistic: "โภชนาการองค์รวม",
    labelAyurveda: "อายุรเวท (แนวทางดั้งเดิม)",
    sourceWord: "ที่มา",
    recTitle: "ดูต่อ",
    recBody: "คอนเทนต์ที่เข้ากับวิญญาณนี้ เร็ว ๆ นี้",
    blockCompare: "เทียบกับวิญญาณอื่น",
    compareYou: "คุณ",
    researchLink: "ดูภาพรวมข้อมูลผู้เล่น (ตัวอย่าง)",
    disclaimer: "เล่นขำ ๆ นะ ไม่ใช่คำแนะนำทางการแพทย์หรือจิตวิทยา",
    igStoryBtn: "ลง IG Story",
    shareBtn: "แชร์",
    retakeBtn: "เล่นใหม่",
    shareMessage: "ชาติก่อนคุณเป็นอะไร? มาเล่นกัน",
    storyHeader: "ตัวอย่างสตอรี่ 9:16",
    storyTitle: "ชาติที่แล้วฉันคือ…",
    storyFooter: "ชาติก่อนคุณเป็นอะไร? 🎟️",
    storyDownload: "บันทึกรูปลงเครื่อง",
    storyClose: "ปิด",
    toastSaved: "บันทึกรูปแล้ว ลงสตอรี่ได้เลย",
    toastCopied: "คัดลอกลิงก์แล้ว (ต้นแบบ)",
    researchBadge: "Illustrative preview — ไม่ใช่ข้อมูลผู้เล่นจริง",
    researchTitle: "แดชบอร์ดสำหรับทีมวิจัย",
    researchClose: "ปิด",
    researchStat1: "ผู้เล่นทั้งหมด", researchStat2: "อาร์คีไทป์ยอดนิยม", researchStat3: "มิติที่โดดเด่น",
    researchInterpretation: "ตัวอย่างข้อมูลนี้ชี้ว่ากลุ่มตัวอย่างอาจชอบคอนเทนต์แนวสำรวจและคิดถึงอดีต ยังสรุปจริงไม่ได้จนกว่าจะมีข้อมูลผู้เล่นจริงมากพอ"
  },
  en: {
    issue: "ISSUE #01 · 1998 → 2026",
    coverLine1: "Special issue! Past lives",
    coverLine2: "Today's lucky colour inside ✦",
    headline1: "What were you",
    headline2: "in your past life?",
    subHook: "Find out in 60 seconds",
    statusLive: "LIVE",
    statusNum: "148,290",
    statusText: "souls discovered",
    todayChip: (c) => `Today's lucky colour: ${c}`,
    birthdayTitle: "Check your sign",
    dayLabel: "Day",
    monthLabel: "Month",
    resultHint: "Pick a day and month to see your sign ✨",
    westernZodiac: "Western zodiac",
    weekdayCaption: "Born on which weekday? (optional · for your birth-day colour)",
    privacyLine: "Only for your sign and colours. No name, no login.",
    startCta: "Unlock my past life →",
    startDisabled: "Pick your birthday first",
    decDay: "Previous day", incDay: "Next day", decMonth: "Previous month", incMonth: "Next month",
    dialAria: (s) => `Zodiac dial: ${s}`,
    backAria: "Back",
    langSwitchAria: "เปลี่ยนเป็นภาษาไทย",
    langOther: "TH",
    prev: "Back",
    next: "Next",
    nextDisabled: "Pick one first",
    seeResult: "Show me!",
    loadingCopy: "Pulling your past-life card…",
    loadingTop: "SOULZINE",
    loadingTravel: "TRAVELLING 1998 → 2026",
    loadingBar: "LOADING",
    resultEyebrow: "SOULZINE · ISSUE #01",
    resultTitle: "Past-life card",
    tabs: ["Card", "You", "Lifestyle", "Compare"],
    revealIntro: "In your past life, you were…",
    rarityTier: "★ ULTRA RARE",
    rarityNote: (p) => `Rarity: ${p}%`,
    sampleData: "sample data",
    tagFun: "For fun",
    tagEvidence: "Sourced",
    tagTradition: "Thai tradition",
    blockBirthday: "Your birthday self",
    elementLabel: "Your element",
    thaiDayLabel: "Birth-day colour",
    horoscopeLabel: "Mini horoscope",
    blockBrief: "Character brief",
    blockToday: (d) => `Today's lucky colours · ${d}`,
    todayHeadline: "Today's lucky colour",
    todaySource: (y) => `Source: Hua Seng Hong · ${y} lucky colours`,
    todayExpired: (y) => `The ${y} table has expired — update pending`,
    blockPop: "Pop-Soul Match",
    popSong: "Soul song", popMovie: "Your movie", popPlace: "Where to go",
    popDecades: "80s → 20s",
    reroll: "Reroll",
    blockEat: "Eat your lucky colour",
    eatCaption: (c) => `From today's lucky colour (${c}) · just for fun, not a prescription`,
    blockZen: "Zen reset",
    zenStart: "Start 3 min",
    zenStop: "Stop",
    zenAgain: "Again",
    blockSelfCare: "A small self-care tip",
    blockGoodToKnow: "Good to know",
    labelHealthyEating: "Healthy eating, simply",
    labelHolistic: "Holistic nutrition",
    labelAyurveda: "Ayurveda (traditional approach)",
    sourceWord: "Source",
    recTitle: "Explore more",
    recBody: "Content picked for this soul — coming soon",
    blockCompare: "Compare souls",
    compareYou: "You",
    researchLink: "View player insights (sample)",
    disclaimer: "Just for fun — this isn't medical or psychological advice.",
    igStoryBtn: "Save IG Story",
    shareBtn: "Share",
    retakeBtn: "Retake",
    shareMessage: "What were you in your past life? Find out:",
    storyHeader: "Story preview 9:16",
    storyTitle: "In my past life I was…",
    storyFooter: "What were you in your past life? 🎟️",
    storyDownload: "Save image",
    storyClose: "Close",
    toastSaved: "Saved! Ready for your story.",
    toastCopied: "Link copied (prototype)",
    researchBadge: "Illustrative preview — not real participant data",
    researchTitle: "Research dashboard",
    researchClose: "Close",
    researchStat1: "Total players", researchStat2: "Top archetype", researchStat3: "Standout dimension",
    researchInterpretation: "This illustrative sample suggests a lean toward exploratory and nostalgic content — not a real conclusion until enough real participant data exists."
  }
};

function t(lang, key, ...args) {
  const val = COPY[lang][key];
  return typeof val === "function" ? val(...args) : val;
}
