// copy.js — UI strings, TH/EN. Tone per Design/DesignLanguage.md.
const COPY = {
  th: {
    scriptMark: "quiz!",
    hookBadgeNum: "148,290",
    hookBadgeCap: "ดวงวิญญาณ\nค้นพบแล้ว",
    headline1: "ชาติที่แล้ว",
    headline2: "คุณเคยเป็นอะไร?",
    subHook: "มาหาคำตอบกันใน 60 วินาที 👀",
    explainer: "ตอบคำถามกวน ๆ 6 ข้อ แล้วจะรู้ว่าชาติก่อนเป็นสัตว์ พืช สิ่งของ หรือไข่มุกชานม",
    birthdayTitle: "เกิดวันไหนเอ่ย?",
    dayLabel: "วันที่",
    monthLabel: "เดือน",
    weekdayLabel: "เกิดวันอะไร? (ไม่บังคับ)",
    weekdaySkip: "ไม่ทราบ / ข้ามได้",
    startCta: "เริ่มเลย",
    startDisabled: "เลือกวันเกิดก่อนน้า",
    privacyLine: "ใช้แค่หาราศีกับสีมงคลนะ ไม่เก็บชื่อ ไม่ต้องล็อกอิน",
    backAria: "ย้อนกลับ",
    questionOf: (n, total) => `ข้อ ${n} / ${total}`,
    nudgeLines: ["เริ่มแล้ว!", "ครึ่งทางแล้ว ไปต่อเลย!", "อีกนิดเดียว", "ข้อสุดท้าย!"],
    loadingCopy: "กำลังย้อนดูชาติก่อน…",
    dashHeader: "SOUL DASHBOARD",
    revealIntro: "ชาติที่แล้วคุณคือ...",
    rarityPrefix: "หายากระดับ",
    rarityLine: (pct) => `คุณคือ ${pct}% ของประชากรที่ได้สิ่งนี้!`,
    illustrativeNote: "(ข้อมูลตัวอย่าง)",
    tagFun: "เอาฮา · FOR FUN",
    tagEvidence: "มีแหล่งอ้างอิง · EVIDENCE-INFORMED",
    blockBirthdayIdentity: "ตัวตนจากวันเกิด",
    zodiacLabel: "ราศีจากวันเกิดคุณ ✨",
    thaiDayLabel: "สีประจำวันเกิด",
    thaiDayUnknown: "ยังไม่ระบุวันเกิด",
    luckyColourLabel: "สีมงคลจากเลขวันเกิด",
    blockCharacterBrief: "ตัวตนย่อ ๆ",
    blockPopCulture: "วิญญาณคู่ป๊อปคัลเจอร์",
    popSong: "เพลง", popMovie: "หนัง", popArt: "งานศิลป์",
    blockEatByColour: "กินตามสีมงคล",
    eatCaption: "เล่นสนุกตามสีนะ ไม่ใช่ใบสั่งอาหาร",
    blockGoodToKnow: "รู้ไว้ก็ดี",
    labelHealthyEating: "กินดีแบบง่าย ๆ",
    labelHolistic: "โภชนาการองค์รวม",
    labelAyurveda: "อายุรเวท (แนวทางดั้งเดิม)",
    blockZen: "พักใจแบบเซน",
    zenStart: "เริ่มจับเวลา",
    zenCancel: "หยุดจับเวลา",
    blockCompare: "เทียบกับวิญญาณอื่น",
    compareNote: "ข้อมูลตัวอย่าง · illustrative",
    igStoryBtn: "ลง IG Story",
    shareBtn: "แชร์ผลลัพธ์",
    shareMessage: "ส่งให้เพื่อนเดา ชาติก่อนเขาเป็นอะไร",
    retakeBtn: "ลองย้อนอีกชาติ",
    recSlotTitle: "อยากรู้เพิ่มไหม?",
    recSlotBody: "แนวทางที่เข้ากับตัวตนนี้ (ยังไม่ใช่สินค้าจริงในตอนนี้)",
    disclaimer: "เล่นขำ ๆ นะ ไม่ใช่คำแนะนำทางการแพทย์หรือจิตวิทยา",
    researchLinkText: "ดูภาพรวมข้อมูลผู้เล่น (ตัวอย่าง)",
    researchBadge: "Illustrative preview — ไม่ใช่ข้อมูลผู้เล่นจริง",
    researchTitle: "แดชบอร์ดสำหรับทีมวิจัย",
    researchClose: "ปิด",
    researchStat1: "ผู้เล่นทั้งหมด", researchStat2: "อาร์คีไทป์ยอดนิยม", researchStat3: "มิติที่โดดเด่น",
    researchInterpretation: "ตัวอย่างข้อมูลนี้ชี้ว่ากลุ่มตัวอย่างอาจมีแนวโน้มชอบคอนเทนต์แนวสำรวจและคิดถึงอดีต — ยังสรุปผลจริงไม่ได้จนกว่าจะมีข้อมูลผู้เล่นจริงมากพอ",
    toastSaved: "บันทึกรูปแล้ว ลงสตอรี่ได้เลย",
    toastCopied: "คัดลอกลิงก์แล้ว",
    storyTitle: "ชาติที่แล้วฉันคือ...",
    storyFooter: "ชาติก่อนคุณเป็นอะไร?",
    storyDownload: "บันทึกรูป",
    storyShare: "แชร์",
    storyClose: "ปิด",
    langToggleAria: "เปลี่ยนภาษา",
  },
  en: {
    scriptMark: "quiz!",
    hookBadgeNum: "148,290",
    hookBadgeCap: "souls already\ndiscovered",
    headline1: "What were you",
    headline2: "in your past life?",
    subHook: "Find out in 60 seconds 👀",
    explainer: "Six silly questions. One very specific past life. It might be a boba pearl.",
    birthdayTitle: "When were you born?",
    dayLabel: "Day",
    monthLabel: "Month",
    weekdayLabel: "Which weekday? (optional)",
    weekdaySkip: "Not sure / skip",
    startCta: "Start Quiz",
    startDisabled: "Pick your birthday first",
    privacyLine: "Just for your zodiac + lucky colour. No name, no login.",
    backAria: "Back",
    questionOf: (n, total) => `Question ${n} of ${total}`,
    nudgeLines: ["Here we go!", "Halfway there, keep going!", "Almost done", "Last one!"],
    loadingCopy: "Rewinding your past lives…",
    dashHeader: "SOUL DASHBOARD",
    revealIntro: "In your past life, you were...",
    rarityPrefix: "Rarity level",
    rarityLine: (pct) => `Only ${pct}% of souls got this.`,
    illustrativeNote: "(sample data)",
    tagFun: "FOR FUN",
    tagEvidence: "EVIDENCE-INFORMED",
    blockBirthdayIdentity: "Your Birthday Identity",
    zodiacLabel: "Your quiz zodiac vibe ✨",
    thaiDayLabel: "Thai day colour",
    thaiDayUnknown: "Weekday not given",
    luckyColourLabel: "Lucky colour from your birth-day number",
    blockCharacterBrief: "Character Brief",
    blockPopCulture: "Pop-Culture Soul Match",
    popSong: "Song", popMovie: "Movie", popArt: "Artwork",
    blockEatByColour: "Eat By Your Lucky Colour",
    eatCaption: "Just a playful colour-food pairing, not a prescription.",
    blockGoodToKnow: "Good To Know",
    labelHealthyEating: "Healthy eating, simply",
    labelHolistic: "Holistic nutrition",
    labelAyurveda: "Ayurveda (traditional approach)",
    blockZen: "Zen Break",
    zenStart: "Start timer",
    zenCancel: "Stop timer",
    blockCompare: "Compare Souls",
    compareNote: "illustrative sample data",
    igStoryBtn: "Save IG Story",
    shareBtn: "Share Result",
    shareMessage: "Make your friends find theirs.",
    retakeBtn: "Try another life",
    recSlotTitle: "Want to explore more?",
    recSlotBody: "A content direction that fits this soul (not a live product yet).",
    disclaimer: "Just for fun — this isn't medical or psychological advice.",
    researchLinkText: "View player insights (sample)",
    researchBadge: "Illustrative preview — not real participant data",
    researchTitle: "Research Dashboard",
    researchClose: "Close",
    researchStat1: "Total players", researchStat2: "Top archetype", researchStat3: "Standout dimension",
    researchInterpretation: "This illustrative sample suggests a relative lean toward exploratory and nostalgic content — not a real conclusion until enough real participant data exists.",
    toastSaved: "Saved! Ready to post to your story.",
    toastCopied: "Link copied",
    storyTitle: "In my past life I was...",
    storyFooter: "What were you in your past life?",
    storyDownload: "Download",
    storyShare: "Share",
    storyClose: "Close",
    langToggleAria: "Switch language",
  }
};

function t(lang, key, ...args) {
  const val = COPY[lang][key];
  return typeof val === "function" ? val(...args) : val;
}
